version: '2'
services:
  database:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  application:
    build: src
    depends_on: [database]
    links:
      - database
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: 'production'
      MONGODB_SETTINGS_HOST: 'database'
